const express = require('express');
const router = express.Router();
const programController = require('../controllers/programController');
const authMiddleware = require('../middlewares/authMiddleware');
const isAdmin = require('../middlewares/isAdmin');
router.get('/program', programController.getAllPrograms);
router.get('/program/:id', programController.getProgramById);
router.post('/program', programController.createProgram);
router.put('/program/:id', programController.updateProgram);
router.delete('/program/:id', programController.deleteProgram);
router.patch('/program/:id/status', programController.updateStatus);
router.patch('/program/:id/view', programController.incrementViews);
router.post('/program/:id/like', programController.addLike);
router.delete('/program/:id/like', programController.removeLike);
router.post('/program/:id/comment', programController.addComment);
router.delete('/program/:id/comment/:commentId', programController.removeComment);
router.get('/program/search', programController.searchPrograms);
router.get('/program/country/:countryId', programController.getProgramsByCountry);
module.exports = router;
